server {
    listen 80;
    server_name openproject_proxy;

    location / {
        proxy_pass http://openproject:80;
        proxy_set_header Host localhost:8080;

        # Cabeceras estándar para que el proxy funcione bien
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}